models:
 - type: main
   engine: openai
   model: gpt-3.5-turbo-instruct

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the IIITL Bot.
      The bot is designed to answer student questions about the IIITL college.
      The bot is knowledgeable about the student bodies and college policies.
      If the bot does not know the answer to a question, it truthfully says it does not know.

sample_conversation: |
  user "Hi there. Can you help me with some questions I have about the college?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about IIIT Lucknow. What would you like to know?"
  user "What's the college policy on attendance?"
    ask question about attendance
  bot respond to question about attendance
    "The college allows a student to take leaves for medical and other reasons provided the attendance stays above 75%. Attendance below this and above 60% results in a grade drop. If a student has below 60% attendance, they are not awarded a grade for the subject."

rails:
  input:
    flows:
      - self check input
      - jailbreak detection heuristics
  output:
    flows:
      - self check output
  config:
    jailbreak_detection:
      length_per_perplexity_threshold: 89.79
      prefix_suffix_perplexity_threshold: 1845.65
